### ISSUE TITLE
Ergonomic problem with i3

### ISSUE THREAD

**Issue by matt-wils0n** [synacktiv/HopLa#1]
Hello, 
Thank you for producing this fantastic tool, which I think is a game changer for the web pentesting community.

The problem I'm having is that the autocomplete window (which is supposed to be a tiny box under the edited text) is considered a new window in i3, which makes it take up half the screen.

Is it possible to investigate this issue?
Thanks for everything.

**Comment by 0x4144** [comment]
Hi,
Thank you for your feedback. I also use i3 on my side, I mentioned in the README.md the line to add in `$HOME/.config/i3/config` to make the autocomplete window floating. You can use this:
`for_window [class=".*burp-StartBurp.*" title="^ $"] floating enable`

Does this fix the problem?

**Comment by matt-wils0n** [comment]
It works so good !.. thank you <3 
Where did you gather the "class" attribute for burp ? I would like to do the same with other programs
Thank you :)

**Comment by 0x4144** [comment]
Hi,
Perfect ! 
To find the "class" you can use `xprop` and search for _WM_CLASS_ value.

**Comment by matt-wils0n** [comment]
Great !
Merci beaucoup.
