### ISSUE TITLE
AutoComplte is Not working 

### ISSUE THREAD

**Issue by d3hack3r** [synacktiv/HopLa#3]
Hello Dude.

I find that auto complete is not working in burp 2021.3.2 .

Can you please check.

![image](https://user-images.githubusercontent.com/64270343/118937436-2d71bd00-b96b-11eb-8ae5-6d54d0013558.png)

**Comment by eyal-gabay** [comment]
same problem here

**Comment by 0x4144** [comment]
Hi, 
Thank you for your feedback. I'll need to output it in the extender to find the origin of the bug.

**Comment by eyal-gabay** [comment]
after i updated the burp it fix +1:

**Comment by 0x4144** [comment]
Nice :)
